#source /home/arne/miniconda3/etc/profile.d/conda.sh;
source /opt/anaconda3/etc/profile.d/conda.sh;
cd deepproblog;
conda activate deepproblog;
python3 addition_final_app.py;
python3 addition_final.py;
cd ..;
cd ntp;
conda activate ntp;
python3 addition_final.py;