source /home/arne/miniconda3/etc/profile.d/conda.sh;
# source /opt/anaconda3/etc/profile.d/conda.sh;
cd deepproblog;
conda activate deepproblog;
python3 addition_final_app.py;
python3 addition_final.py;
python3 addition_final_app_1.py;
python3 addition_final_app_25.py;
python3 addition_final_app_5.py;
python3 addition_final_1.py;
python3 addition_final_25.py;
python3 addition_final_5.py;
