source /home/arne/miniconda3/etc/profile.d/conda.sh;
#source /opt/anaconda3/etc/profile.d/conda.sh;
cd deepstochlog;
conda activate deepstochlog;
python3 addition_final.py;
python3 addition_final_1.py;
python3 addition_final_25.py;
python3 addition_final_5.py;
cd ..;
cd logic_tensor_networks;
conda activate logic_tensor_networks;
python3 addition_final.py;
python3 addition_final_1.py;
python3 addition_final_25.py;
python3 addition_final_5.py;
cd ..;
cd neurasp;
conda activate neurasp;
python3 addition_final.py;
python3 addition_final_1.py;
python3 addition_final_25.py;
python3 addition_final_5.py;
cd ..;
cd nn;
conda activate deepproblog;
python3 addition_final.py;
python3 addition_final_1.py;
python3 addition_final_25.py;
python3 addition_final_5.py;
cd ..;
cd semantic_loss_1_label;
python3 addition_final.py;
python3 addition_final_1.py;
python3 addition_final_25.py;
python3 addition_final_5.py;
cd ..;
cd deepproblog;
conda activate deepproblog;
python3 addition_final.py;
python3 addition_final_1.py;
python3 addition_final_25.py;
python3 addition_final_5.py;
python3 addition_final_app.py;
python3 addition_final_app_1.py;
python3 addition_final_app_25.py;
python3 addition_final_app_5.py;
