source /opt/anaconda3/etc/profile.d/conda.sh;
cd semantic_loss_1_label;
python3 addition_param.py;
cd ..;
cd nn;
conda deactivate;
python3 addition_param.py;
cd ..;
cd deepproblog;
conda activate deepproblog;
python3 addition_param_app.py;
python3 addition_param.py;
cd ..;
cd deepstochlog;
conda activate deepstochlog;
python3 addition_param.py;
cd ..;
cd logic_tensor_networks;
conda activate logic_tensor_networks;
python3 addition_param.py;
cd ..;
cd neurasp;
conda activate neurasp;
python3 addition_param.py;