source /home/arne/miniconda3/etc/profile.d/conda.sh;
# source /opt/anaconda3/etc/profile.d/conda.sh;
# cd nn;
# conda activate deepproblog;
# python3 addition_param.py;
# cd ..;
# cd neurasp;
# conda activate neurasp;
# python3 addition_param.py;
# cd ..;
# cd logic_tensor_networks;
# conda activate logic_tensor_networks;
# python3 1_addition_final.py;
# python3 2_addition_final.py;
# python3 3_addition_final.py;
# python3 4_addition_final.py;
cd semantic_loss;
conda activate semantic_loss;
python3 1_addition_final.py;
python3 2_addition_final.py;
python3 3_addition_final.py;
# cd ..;
# cd deepstochlog;
# conda activate deepstochlog;
# python3 addition_param.py;
# cd ..;
# cd deepproblog;
# conda activate deepproblog;
# python3 addition_param.py;
# python3 addition_param_app.py;