addition(x,y,0) :- digit(x,0), digit(y,0).
addition(x,y,1) :- digit(x,1), digit(y,0).
addition(x,y,2) :- digit(x,2), digit(y,0).
addition(x,y,3) :- digit(x,3), digit(y,0).
addition(x,y,4) :- digit(x,4), digit(y,0).
addition(x,y,5) :- digit(x,5), digit(y,0).
addition(x,y,6) :- digit(x,6), digit(y,0).
addition(x,y,7) :- digit(x,7), digit(y,0).
addition(x,y,8) :- digit(x,8), digit(y,0).
addition(x,y,9) :- digit(x,9), digit(y,0).
addition(x,y,1) :- digit(x,0), digit(y,1).
addition(x,y,2) :- digit(x,1), digit(y,1).
addition(x,y,3) :- digit(x,2), digit(y,1).
addition(x,y,4) :- digit(x,3), digit(y,1).
addition(x,y,5) :- digit(x,4), digit(y,1).
addition(x,y,6) :- digit(x,5), digit(y,1).
addition(x,y,7) :- digit(x,6), digit(y,1).
addition(x,y,8) :- digit(x,7), digit(y,1).
addition(x,y,9) :- digit(x,8), digit(y,1).
addition(x,y,10) :- digit(x,9), digit(y,1).
addition(x,y,2) :- digit(x,0), digit(y,2).
addition(x,y,3) :- digit(x,1), digit(y,2).
addition(x,y,4) :- digit(x,2), digit(y,2).
addition(x,y,5) :- digit(x,3), digit(y,2).
addition(x,y,6) :- digit(x,4), digit(y,2).
addition(x,y,7) :- digit(x,5), digit(y,2).
addition(x,y,8) :- digit(x,6), digit(y,2).
addition(x,y,9) :- digit(x,7), digit(y,2).
addition(x,y,10) :- digit(x,8), digit(y,2).
addition(x,y,11) :- digit(x,9), digit(y,2).
addition(x,y,3) :- digit(x,0), digit(y,3).
addition(x,y,4) :- digit(x,1), digit(y,3).
addition(x,y,5) :- digit(x,2), digit(y,3).
addition(x,y,6) :- digit(x,3), digit(y,3).
addition(x,y,7) :- digit(x,4), digit(y,3).
addition(x,y,8) :- digit(x,5), digit(y,3).
addition(x,y,9) :- digit(x,6), digit(y,3).
addition(x,y,10) :- digit(x,7), digit(y,3).
addition(x,y,11) :- digit(x,8), digit(y,3).
addition(x,y,12) :- digit(x,9), digit(y,3).
addition(x,y,4) :- digit(x,0), digit(y,4).
addition(x,y,5) :- digit(x,1), digit(y,4).
addition(x,y,6) :- digit(x,2), digit(y,4).
addition(x,y,7) :- digit(x,3), digit(y,4).
addition(x,y,8) :- digit(x,4), digit(y,4).
addition(x,y,9) :- digit(x,5), digit(y,4).
addition(x,y,10) :- digit(x,6), digit(y,4).
addition(x,y,11) :- digit(x,7), digit(y,4).
addition(x,y,12) :- digit(x,8), digit(y,4).
addition(x,y,13) :- digit(x,9), digit(y,4).
addition(x,y,5) :- digit(x,0), digit(y,5).
addition(x,y,6) :- digit(x,1), digit(y,5).
addition(x,y,7) :- digit(x,2), digit(y,5).
addition(x,y,8) :- digit(x,3), digit(y,5).
addition(x,y,9) :- digit(x,4), digit(y,5).
addition(x,y,10) :- digit(x,5), digit(y,5).
addition(x,y,11) :- digit(x,6), digit(y,5).
addition(x,y,12) :- digit(x,7), digit(y,5).
addition(x,y,13) :- digit(x,8), digit(y,5).
addition(x,y,14) :- digit(x,9), digit(y,5).
addition(x,y,6) :- digit(x,0), digit(y,6).
addition(x,y,7) :- digit(x,1), digit(y,6).
addition(x,y,8) :- digit(x,2), digit(y,6).
addition(x,y,9) :- digit(x,3), digit(y,6).
addition(x,y,10) :- digit(x,4), digit(y,6).
addition(x,y,11) :- digit(x,5), digit(y,6).
addition(x,y,12) :- digit(x,6), digit(y,6).
addition(x,y,13) :- digit(x,7), digit(y,6).
addition(x,y,14) :- digit(x,8), digit(y,6).
addition(x,y,15) :- digit(x,9), digit(y,6).
addition(x,y,7) :- digit(x,0), digit(y,7).
addition(x,y,8) :- digit(x,1), digit(y,7).
addition(x,y,9) :- digit(x,2), digit(y,7).
addition(x,y,10) :- digit(x,3), digit(y,7).
addition(x,y,11) :- digit(x,4), digit(y,7).
addition(x,y,12) :- digit(x,5), digit(y,7).
addition(x,y,13) :- digit(x,6), digit(y,7).
addition(x,y,14) :- digit(x,7), digit(y,7).
addition(x,y,15) :- digit(x,8), digit(y,7).
addition(x,y,16) :- digit(x,9), digit(y,7).
addition(x,y,8) :- digit(x,0), digit(y,8).
addition(x,y,9) :- digit(x,1), digit(y,8).
addition(x,y,10) :- digit(x,2), digit(y,8).
addition(x,y,11) :- digit(x,3), digit(y,8).
addition(x,y,12) :- digit(x,4), digit(y,8).
addition(x,y,13) :- digit(x,5), digit(y,8).
addition(x,y,14) :- digit(x,6), digit(y,8).
addition(x,y,15) :- digit(x,7), digit(y,8).
addition(x,y,16) :- digit(x,8), digit(y,8).
addition(x,y,17) :- digit(x,9), digit(y,8).
addition(x,y,9) :- digit(x,0), digit(y,9).
addition(x,y,10) :- digit(x,1), digit(y,9).
addition(x,y,11) :- digit(x,2), digit(y,9).
addition(x,y,12) :- digit(x,3), digit(y,9).
addition(x,y,13) :- digit(x,4), digit(y,9).
addition(x,y,14) :- digit(x,5), digit(y,9).
addition(x,y,15) :- digit(x,6), digit(y,9).
addition(x,y,16) :- digit(x,7), digit(y,9).
addition(x,y,17) :- digit(x,8), digit(y,9).
addition(x,y,18) :- digit(x,9), digit(y,9).